version: '3'
services:
  wbserver:
    restart: always
    build: .
    environment:
      - RUNNING_ENV=production
    ports:
      - "8090:3000"
      - "80:80"
    volumes:
      - /home/whiteboard-web:/home/whiteboard-web
      - /home/server-logs:/home/logs
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass123
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /home/postgre/data:/var/lib/postgresql/data/pgdata